name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install -r day5/requirements.txt

    - name: Run tests
      run: |
        pytest day5/演習3/tests

    - name: Format check with black
      run: black --check day5/演習3/

    - name: Lint check with flake8 (allow 88-char lines)
      run: flake8 day5/演習3/ --max-line-length=88
